version: '3.8'

services:
  hbase:
    image: "${HBASE_IMAGE}"
    container_name: hbase-docker
    hostname: hbase-docker
    ports:
      - "8000:8000"
      - "8765:8765"
      - "8080:8080"
      - "8085:8085"
      - "9090:9090"
      - "9095:9095"
      - "2181:2181"
      - "16000:16000"
      - "16010:16010"
      - "16020:16020"
      - "16030:16030"
    networks:
      - geoserver-hbase-network

  geoserver:
    image: "${GEOSERVER_IMAGE}"
    container_name: geoserver-docker
    hostname: geoserver-docker
    ports:
      - "8081:8080"
    networks:
      - geoserver-hbase-network

networks:
  geoserver-hbase-network:
    driver: bridge
